server:
  port: 8080
  servlet:
    context-path: /secureTest
spring:
  datasource:
    name: mysql
    url: jdbc:mysql://127.0.0.1:3306/spring_security
    username: mysql
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
#  mvc:
#    view:
#      prefix: classpath:/static/views
#      suffix: .html
  thymeleaf:
    servlet:
      content-type: text/html
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/static/views/
    suffix: .html

